name: Build Multi-Platform Executables
on:
  push:
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0

permissions:
  contents: write # This is crucial for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller
      
      - name: Install additional Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      
      - name: Create PyInstaller spec file
        run: |
          echo "# -*- mode: python -*-
          block_cipher = None
          a = Analysis(['main.py'],
                      pathex=['.'],
                      binaries=[],
                      datas=[],
                      hiddenimports=['pygame'],
                      hookspath=[],
                      runtime_hooks=[],
                      excludes=[],
                      win_no_prefer_redirects=False,
                      win_private_assemblies=False,
                      cipher=block_cipher,
                      noarchive=False)
          pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
          exe = EXE(pyz,
                   a.scripts,
                   a.binaries,
                   a.zipfiles,
                   a.datas,
                   [],
                   name='BresenhamLine',
                   debug=False,
                   bootloader_ignore_signals=False,
                   strip=False,
                   upx=True,
                   upx_exclude=[],
                   runtime_tmpdir=None,
                   console=False,
                   disable_windowed_traceback=False,
                   argv_emulation=False,
                   target_arch=None,
                   codesign_identity=None,
                   entitlements_file=None)
          " > build.spec
      
      - name: Build with PyInstaller
        run: pyinstaller build.spec
        
      # Zip the executable files for easier download
      - name: Zip Windows executable
        if: runner.os == 'Windows'
        run: |
          cd dist
          Compress-Archive -Path BresenhamLine.exe -DestinationPath BresenhamLine-Windows.zip
      
      - name: Zip macOS executable
        if: runner.os == 'macOS'
        run: |
          cd dist
          zip -r BresenhamLine-macOS.zip BresenhamLine
      
      - name: Zip Linux executable
        if: runner.os == 'Linux'
        run: |
          cd dist
          zip -r BresenhamLine-Linux.zip BresenhamLine
      
      # Keep artifacts for debugging and quick access
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BresenhamLine-${{ runner.os }}
          path: dist/BresenhamLine*
      
      # Upload to GitHub Release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/BresenhamLine-*.zip
          name: Bresenham Line ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}